### PR TITLE
expand treeview item if it's the only available repository

### PR DESCRIPTION
**Pull request by lelmarir**

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
Wonderful!
Related ideas:
https://github.com/aegif/CmisSync/issues/585
https://github.com/aegif/CmisSync/issues/586
https://github.com/aegif/CmisSync/issues/229

**Comment by lelmarir** [comment]
haha, you have anticipated me merging this.
anyway i'm working on a complete rewrite of the Add2 page (and probably Add1)

**Comment by nicolas-raoul** [comment]
Great! Looking forward to the rewrite :-)
By the way, the Mac and Linux implementations seriously lag behind...

If you plan change to Add1, could you please first create a [new issue](https://github.com/aegif/CmisSync/issues/new) describing the changes, so that we can discuss ideas? Thanks a lot!

**Comment by lelmarir** [comment]
I'm still a neophyte on Visual Studio and c#. Is the Mac and Linux code a separated one? Is it not the same?

**Comment by nicolas-raoul** [comment]
Unfortunately, the Mac and Linux code is similar but different, using different (more native) technologies.

**Comment by lelmarir** [comment]
I'll try to look into it

**Pull request merged**
